# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:
    branches: [ "main", "MauricioLeaño_p1_dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: load dependencies
        run: dotnet restore

      - name: load ReSharper
        run: dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path ../toolsDev
      - name: load report generator
        run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path ../toolsDev

      - name: generate report
        run: ../toolsDev/jb inspectcode ./TrainProject.sln -o=./reports/report

      - name: run tests
        run: cd .\myApp.Tests\ | dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=reports/coverage 
